[package]
name = "stream_of_characters"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "stream_of_characters"
path = "stream_of_characters.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
