[package]
name = "shuffle_an_array"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "shuffle_an_array"
path = "shuffle_an_array.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
