[package]
name = "arithmetic_slices"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "arithmetic_slices"
path = "arithmetic_slices.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
