[package]
name = "single_element_in_a_sorted_array"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "single_element_in_a_sorted_array"
path = "single_element_in_a_sorted_array.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
