[package]
name = "complement_of_base_10_integer"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "complement_of_base_10_integer"
path = "complement_of_base_10_integer.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
