[package]
name = "find_median_from_data_stream"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "find_median_from_data_stream"
path = "find_median_from_data_stream.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
